"""Initial schema

Revision ID: 42b0437acfe2
Revises: 
Create Date: 2026-09-18 09:19:56.311812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0437acfe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('team_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], name=op.f('fk_teams_team_lead_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('state_scope', sa.String(length=500), nullable=True),
    sa.Column('is_active_employee', sa.Boolean(), nullable=False),
    sa.Column('resigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bulk_upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_bulk_upload_batches_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_upload_batches'))
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('bulk_batch_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_leads_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['bulk_batch_id'], ['bulk_upload_batches.id'], name=op.f('fk_leads_bulk_batch_id_bulk_upload_batches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_leads_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_leads_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('from_employee_id', sa.Integer(), nullable=True),
    sa.Column('to_employee_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_assignment_history_changed_by_id_users')),
    sa.ForeignKeyConstraint(['from_employee_id'], ['users.id'], name=op.f('fk_assignment_history_from_employee_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_assignment_history_lead_id_leads')),
    sa.ForeignKeyConstraint(['to_employee_id'], ['users.id'], name=op.f('fk_assignment_history_to_employee_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_history'))
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('call_time', sa.DateTime(), nullable=True),
    sa.Column('status_set', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_call_logs_employee_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_call_logs_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_enrollments_created_by_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_enrollments_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('lead_id', name=op.f('uq_enrollments_lead_id'))
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_follow_ups_employee_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_follow_ups_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_ups')
    op.drop_table('enrollments')
    op.drop_table('call_logs')
    op.drop_table('assignment_history')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_state'))
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_assigned_to_id'))

    op.drop_table('leads')
    op.drop_table('bulk_upload_batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
